---
repos:
  - repo: https://github.com/timhourigan/pre-commit-hooks
    rev: 0.1.0
    hooks:
      - id: black
        stages: [commit]
      - id: flake8
        stages: [commit]
        args: [--config=setup.cfg]
      - id: isort
        stages: [commit]
        args: [--settings-file=setup.cfg]
